name: GitHub Actions

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 22
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install PNPM
        run: npm i -g pnpm
      - name: Install & Build
        run: pnpm i  &&  pnpm build
      # - run: npm test

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install PNPM
        run: npm i -g pnpm
      - name: Check
        run: pnpm run check
